<template>
    <main class="w-full py-20 overflow-y-clip flex items-center justify-center">
        <div class="w-full min-h-full flex flex-col px-20 items-center justify-between">
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
            <p>tes</p>
        </div>
    </main>
</template>